const travelKeywords = [
    // General Travel
    'adventure',
    'backpacking',
    'budget travel',
    'cultural experience',
    'eco-tourism',
    'family vacation',
    'hiking',
    'holiday',
    'luxury travel',
    'road trip',
    'sightseeing',
    'solo travel',
    'tourist attractions',
    'vacation',
    'wanderlust',

    // Pakistan Specific
    'Hunza Valley',
    'Karakoram Highway',
    'Lahore Fort',
    'Badshahi Mosque',
    'K2',
    'Nanga Parbat',
    'Swat Valley',
    'Gilgit-Baltistan',
    'Chitral',
    'Murree',
    'Islamabad',
    'Karachi',
    'Peshawar',
    'Multan',
    'Faisal Mosque',

    // Activities
    'mountain climbing',
    'trekking',
    'camping',
    'photography',
    'local cuisine',
    'shopping',
    'cultural festivals',
    'wildlife safari',
    'historical tours',
    'religious sites',
    'beach activities',
    'desert safari',
    'river rafting',
    'skiing',
    'bird watching',

    // Seasons
    'spring travel',
    'summer vacation',
    'autumn trips',
    'winter holidays',
    'peak season',
    'off season',
    'shoulder season',
    'monsoon travel',
    'festival season',

    // Planning
    'itinerary',
    'accommodation',
    'transportation',
    'travel insurance',
    'visa requirements',
    'travel documents',
    'packing list',
    'budget planning',
    'local currency',
    'travel tips',

    // Pakistani Culture & Heritage
    'Sufi shrines',
    'Mughal architecture',
    'traditional crafts',
    'local bazaars',
    'Pakistani cuisine',
    'cultural festivals',
    'traditional music',
    'handicrafts',
    'historical monuments',
    'religious diversity'
];

module.exports = travelKeywords; 