const travelKeywords = [
    // General Travel
    'adventure',
    'backpacking',
    'budgettravel',
    'culturalexperience',
    'eco-tourism',
    'familyvacation',
    'hiking',
    'holiday',
    'luxurytravel',
    'roadtrip',
    'sightseeing',
    'solotravel',
    'touristattractions',
    'vacation',
    'wanderlust',

    // Pakistan Specific
    'HunzaValley',
    'KarakoramHighway',
    'LahoreFort',
    'BadshahiMosque',
    'K2',
    'NangaParbat',
    'SwatValley',
    'Gilgit-Baltistan',
    'Chitral',
    'Murree',
    'Islamabad',
    'Karachi',
    'Peshawar',
    'Multan',
    'FaisalMosque',
    'Quetta',
    'Sialkot',
    'Faisalabad',
    'Hyderabad',
    'Sukkur',
    'Gujranwala',
    'Rawalpindi',
    'Bahawalpur',
    'Sargodha',
    'Gujrat',
    'Mardan',
    'Larkana',
    'RahimYarKhan',
    'Sheikhupura',
    'Jhang',
    'Sahiwal',
    'WahCantonment',
    'Mingora',
    'Okara',
    'MirpurKhas',
    'Chiniot',
    'Kamoke',
    'Hafizabad',
    'Sadiqabad',
    'Burewala',
    'Kohat',

    // Activities
    'mountainclimbing',
    'trekking',
    'camping',
    'photography',
    'local cuisine',
    'shopping',
    'culturalfestivals',
    'wildlifesafari',
    'historicaltours',
    'religioussites',
    'beachactivities',
    'desertsafari',
    'riverrafting',
    'skiing',
    'birdwatching',

    // Seasons
    'springtravel',
    'summervacation',
    'autumntrips',
    'winterholidays',
    'peakseason',
    'offseason',
    'shoulderseason',
    'monsoontravel',
    'festivalseason',

    // Planning
    'itinerary',
    'accommodation',
    'transportation',
    'travelinsurance',
    'visarequirements',
    'traveldocuments',
    'packinglist',
    'budgetplanning',
    'localcurrency',
    'traveltips',

    // Pakistani Culture & Heritage
    'Sufishrines',
    'Mughalarchitecture',
    'traditionalcrafts',
    'localbazaars',
    'Pakistanicuisine',
    'traditionalmusic',
    'handicrafts',
    'historicalmonuments',
    'religiousdiversity'
];

module.exports = travelKeywords; 