name: Deploy Backend to DigitalOcean

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        working-directory: backend
        run: npm install

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: afaq
          script: |
            cd /var/www/Explorely/backend
            git pull origin main
            npm install
            pm2 restart explorely-backend
